name: Build macOS and Windows Binaries

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: npm install
      - run: npm run tauri build

      - name: Upload EXE
        uses: actions/upload-artifact@v3.1.3
        with:
          name: windows-exe
          path: src-tauri/target/release/bundle/windows/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "source $HOME/.cargo/env" >> $GITHUB_ENV

      - run: |
          source $HOME/.cargo/env
          npm install
      - run: |
          source $HOME/.cargo/env
          npm run tauri build

      - name: Upload .app
        uses: actions/upload-artifact@v3.1.3
        with:
          name: macos-app
          path: src-tauri/target/release/bundle/macos/
